#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csc8019group8
    username: root
#    password: 1234
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis日志和驼峰命名
mybatis:
  #mapper配置文件
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.warehouse.pojo

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      warehouse:
        dao: debug
        service: info
        controller: info
    org.springframework.jdbc.support.JdbcTransactionManager: debug


#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'com.warehouse'
      paths-to-match: '/**'
      packages-to-scan: com.warehouse  #改成你自己的包名，一般到启动类的包名

#knife4j相关配置 可以不用改
knife4j:
  enable: false
  setting:
    language: zh_cn
    swagger-model-name: 实体类
stripe:
  api:
    key: sk_test_51P56SkRqfEvDhP7Fqxdg89eozoT7WgkgK2BJvvCKJlErYAtci7CjY3Q2O8sMHExkp09QlZgnqqd4I5wW3asGDt6g00x1Ar34hu

